### ISSUE TITLE
Not an issue per se

### ISSUE THREAD

**Issue by DonRomaniello** [kprinssu/osx-razer-blade#2]
Thank you for porting this, and sorry if this information is available elsewhere, but I'm trying to set my keyboard to a specific RGB value and I can't for the life of me figure out how to designate a static color.

`razer_attr_write_mode_static(dev, "1", ?????);`

The question marks is where I'm stuck.

**Comment by dylanparker** [comment]
Hey @DonRomaniello 

That third param for `razer_attr_write_mode_static` is always 3 since it is expecting 3 colour values encoded in the second parameter.

Check out [this code](https://github.com/dylanparker/osx-razer-led/blob/master/src/main.c#L137) in my [osx-razer-led](https://github.com/dylanparker/osx-razer-led) repo that I extended from this repo. It should explain how the RGB is encoded into `buf` to get the colour you want.

**Comment by DonRomaniello** [comment]
Thank you @dylanparker, I'm actually currently using osx-razer-led in a script executed at launch to set my keyboard leds.



Got it. I have to declare char buf[3] and put the values in beforehand. Thank you for pointing me in the right direction. Or rather, explaining exactly what to do provided I knew enough C to figure it out...  it probably has to do with the fact that 95% of the coding I've done has been for the Arduino and has involved a fair amount of cut and paste.

**Comment by dylanparker** [comment]
> Thank you @dylanparker, I'm actually currently using osx-razer-led in a script executed at launch to set my keyboard leds. 

Nice! Glad you are finding it useful.

> Got it. I have to declare char buf[3] and put the values in beforehand. Thank you for pointing me in the right direction. Or rather, explaining exactly what to do provided I knew enough C to figure it out... it probably has to do with the fact that 95% of the coding I've done has been for the Arduino and has involved a fair amount of cut and paste.

No problem. Good luck.
